routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('mainhome');
Route::get('posts', 'PostController@index')->name('posts.index');
Route::get('post/{slug}', 'PostController@details')->name('post.details');
Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');

});

/* Admin route */
Route::group([
    'as'         => 'admin.',
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => ['auth', 'admin'],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('pending/post', 'PostController@pending')->name('post.pending');
    Route::put('post/{post}/approve', 'PostController@approval')->name('post.approve');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');
});

/* Author route */
Route::group([
    'as'         => 'author.',
    'prefix'     => 'author',
    'namespace'  => 'Author',
    'middleware' => ['auth', 'author'],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('post', 'PostController');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');
});

resources/views/layouts/backend/partial/sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="image">
            <img src="{{asset('public/storage/profile/'.Auth::user()->image)}}" width="48" height="48" alt="User"/>
        </div>
        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true"
                 aria-expanded="false">{{Auth::user()->name}}</div>
            <div class="email">{{Auth::user()->email}}</div>
            <div class="btn-group user-helper-dropdown">
                <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                <ul class="dropdown-menu pull-right">

                    <li><a href="{{ Auth::user()->role_id == 1 ? route('admin.settings') : route('author.settings') }}"><i
                                class="material-icons">settings</i>Settings</a></li>

                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="material-icons">input</i>{{ __('Sign Out') }}
                        </a>

                        <form id="logout-form-dp" action="{{ route('logout') }}" method="POST"
                              style="display: none;">
                            @csrf
                        </form>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>

            <!-- Admin menu items -->
            @if(Request::is('admin*'))

                <li class="{{Request::is('admin/dashboard') ? 'active' : ''}}">
                    <a href="{{route('admin.dashboard')}}">
                        <i class="material-icons">dashboard</i>
                        <span>{{ __('Dashboard') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('admin/tag*') ? 'active' : ''}}">
                    <a href="{{route('admin.tag.index')}}">
                        <i class="material-icons">label</i>
                        <span>{{ __('Tags') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('admin/category*') ? 'active' : ''}}">
                    <a href="{{route('admin.category.index')}}">
                        <i class="material-icons">apps</i>
                        <span>{{ __('Categories') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('admin/post*') ? 'active' : ''}}">
                    <a href="{{route('admin.post.index')}}">
                        <i class="material-icons">library_books</i>
                        <span>{{ __('Posts') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('admin/pending/post') ? 'active' : ''}}">
                    <a href="{{route('admin.post.pending')}}">
                        <i class="material-icons">library_books</i>
                        <span>{{ __('Pending Posts') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('admin/favorite') ? 'active' : ''}}">
                    <a href="{{route('admin.favorite.index')}}">
                        <i class="material-icons">favorite</i>
                        <span>{{ __('Favorite Posts') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('admin/settings') ? 'active' : ''}}">
                    <a href="{{route('admin.settings')}}">
                        <i class="material-icons">settings</i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                </li>

                <li class="header">SYSTEM</li>

                <li class="{{Request::is('admin/subscriber') ? 'active' : ''}}">
                    <a href="{{route('admin.subscriber.index')}}">
                        <i class="material-icons">subscriptions</i>
                        <span>{{ __('Subscribers') }}</span>
                    </a>
                </li>

                <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="material-icons">input</i>
                        <span>{{ __('Sign Out') }}</span>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>
                </li>

            @endif
        <!-- End: Admin menu items -->

            <!-- Author menu items -->
            @if(Request::is('author*'))

                <li class="{{Request::is('author/dashboard') ? 'active' : ''}}">
                    <a href="{{route('author.dashboard')}}">
                        <i class="material-icons">dashboard</i>
                        <span>{{ __('Dashboard') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('author/post*') ? 'active' : ''}}">
                    <a href="{{route('author.post.index')}}">
                        <i class="material-icons">library_books</i>
                        <span>{{ __('Posts') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('author/favorite') ? 'active' : ''}}">
                    <a href="{{route('author.favorite.index')}}">
                        <i class="material-icons">favorite</i>
                        <span>{{ __('Favorite Posts') }}</span>
                    </a>
                </li>

                <li class="{{Request::is('author/settings') ? 'active' : ''}}">
                    <a href="{{route('author.settings')}}">
                        <i class="material-icons">settings</i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                </li>

                <li class="header">SYSTEM</li>

                <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="material-icons">input</i>
                        <span>{{ __('Sign Out') }}</span>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>
                </li>

        @endif
        <!-- End: Author menu items -->

        </ul>
    </div>
    <!-- #Menu -->
    <!-- Footer -->
    <div class="legal">
        <div class="copyright">
            &copy; 2020 - 2021 <a href="javascript:void(0);">Laravel - lBlog</a>.
        </div>
    </div>
    <!-- #Footer -->
</aside>

resources/views/layouts/backend/partial/topbar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse"
               data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="index.html">Laravel - lBlog</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <li><a href="javascript:void(0);" class="js-search" data-close="true"><i
                            class="material-icons">search</i></a></li>
                <!-- #END# Call Search -->
            </ul>
        </div>
    </div>
</nav>