routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('mainhome');
Route::get('posts', 'PostController@index')->name('posts.index');
Route::get('post/{slug}', 'PostController@details')->name('post.details');
Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');

});

/* Admin route */
Route::group([
    'as'         => 'admin.',
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => ['auth', 'admin'],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('pending/post', 'PostController@pending')->name('post.pending');
    Route::put('post/{post}/approve', 'PostController@approval')->name('post.approve');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');
});

/* Author route */
Route::group([
    'as'         => 'author.',
    'prefix'     => 'author',
    'namespace'  => 'Author',
    'middleware' => ['auth', 'author'],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('post', 'PostController');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category')->withTimestamps();
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag')->withTimestamps();
    }

    public function favorite_to_users()
    {
        return $this->belongsToMany('App\User')->withTimestamps();
    }

}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Notifications\AuthorPostApproved;
use App\Notifications\NewPostNotify;
use App\Post;
use App\Subscriber;
use App\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use function compact;
use function redirect;
use function route;
use function str_slug;
use function uniqid;
use function view;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $posts = Post::latest()->get();

        return view('admin.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::all();
        $tags       = Tag::all();

        return view('admin.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'      => 'required',
            'image'      => 'required|mimes:jpeg,png,jpg',
            'categories' => 'required',
            'tags'       => 'required',
            'body'       => 'required',
        ]);

        // Get form image
        $image = $request->file('image');
        $slug  = str_slug($request->title);

        if (isset($image)) {

            // make unique name
            $currentDate = Carbon::now()->toDateString();
            $imageName   = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            // check if directory is exists
            if ( ! Storage::disk('public')->exists('post')) {
                Storage::disk('public')->makeDirectory('post');
            }

            // resize image for category
            $postImage = Image::make($image)->fit(1600, 1066)->stream();
            Storage::disk('public')->put('post/' . $imageName, $postImage);

        } else {

            $imageName = 'default.jpg';

        }

        $post          = new Post();
        $post->user_id = Auth::id();
        $post->title   = $request->title;
        $post->slug    = $slug;
        $post->image   = $imageName;
        $post->body    = $request->body;
        if (isset($request->status)) {
            $post->status = TRUE;
        } else {
            $post->status = FALSE;
        }
        $post->is_approved = TRUE;
        $post->save();

        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);

        $subscribers = Subscriber::all();

        foreach ($subscribers as $subscriber) {
            Notification::route('mail', $subscriber->email)
                        ->notify(new NewPostNotify($post));
        }

        return redirect(route('admin.post.index'))->with('successMsg', 'Post created successfully!');

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Post $post
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Post $post)
    {
        return view('admin.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Post $post
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags       = Tag::all();

        return view('admin.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Post                $post
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request, [
            'title'      => 'required',
            'image'      => 'mimes:jpeg,png,jpg',
            'categories' => 'required',
            'tags'       => 'required',
            'body'       => 'required',
        ]);

        // Get form image
        $image = $request->file('image');
        $slug  = str_slug($request->title);

        if (isset($image)) {

            // make unique name
            $currentDate = Carbon::now()->toDateString();
            $imageName   = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            // delete old image
            if (Storage::disk('public')->exists('post/' . $post->image)) {
                Storage::disk('public')->delete('post/' . $post->image);
            }

            // check if directory is exists
            if ( ! Storage::disk('public')->exists('post')) {
                Storage::disk('public')->makeDirectory('post');
            }

            // resize image for category
            $postImage = Image::make($image)->fit(1600, 1066)->stream();
            Storage::disk('public')->put('post/' . $imageName, $postImage);

        } else {

            $imageName = $post->image;

        }

        $post->user_id = Auth::id();
        $post->title   = $request->title;
        $post->slug    = $slug;
        $post->image   = $imageName;
        $post->body    = $request->body;
        if (isset($request->status)) {
            $post->status = TRUE;
        } else {
            $post->status = FALSE;
        }
        $post->is_approved = TRUE;
        $post->save();

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);

        return redirect(route('admin.post.index'))->with('successMsg', 'Post updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Post $post
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Post $post)
    {
        // delete old image
        if (Storage::disk('public')->exists('post/' . $post->image)) {
            Storage::disk('public')->delete('post/' . $post->image);
        }

        $post->categories()->detach();
        $post->tags()->detach();
        $post->delete();

        return redirect(route('admin.post.index'))->with('successMsg', 'Post deleted successfully!');
    }

    public function pending()
    {

        $posts = Post::where('is_approved', FALSE)->get();

        return view('admin.post.pending', compact('posts'));

    }

    public function approval(Post $post)
    {
//        $post = Post::find($id);

        if ($post->is_approved == FALSE) {
            $post->is_approved = TRUE;
            $post->save();

            $post->user->notify(new AuthorPostApproved($post));

            $subscribers = Subscriber::all();

            foreach ($subscribers as $subscriber) {
                Notification::route('mail', $subscriber->email)
                            ->notify(new NewPostNotify($post));
            }

            return redirect(route('admin.post.pending'))->with('successMsg', 'Post approved successfully!');
        } else {
            return redirect(route('admin.post.pending'))->with('successMsg', 'Post is already approved!');
        }

    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use function view;

class DashboardController extends Controller
{
    public function index()
    {
        return view('author.dashboard');
    }
}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use function compact;
use function view;

class FavoriteController extends Controller
{
    public function index() {

        $posts = Auth::user()->favorite_posts;

        return view('admin.favorite', compact('posts'));

    }
}

app/Http/Controllers/Author/SettingsController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use App\User;
use Auth;
use Carbon\Carbon;
use Hash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use function redirect;
use function str_slug;
use function uniqid;
use function view;

class SettingsController extends Controller
{
    public function index()
    {

        return view('author.settings');
    }

    public function updateProfile(Request $request)
    {

        $this->validate($request, [
            'name'  => 'required',
            'email' => 'required|email',
            'image' => 'image',
        ]);

        // Get form image
        $image = $request->file('image');
        $slug  = str_slug($request->name);
        $user  = User::findOrFail(Auth::id());

        if (isset($image)) {

            // delete old image from user dir
            if (Storage::disk('public')->exists('profile/' . $user->image)) {
                Storage::disk('public')->delete('profile/' . $user->image);
            }

            // make unique name
            $currentdate = Carbon::now()->toDateString();
            $imageName   = $slug . '-' . $currentdate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            // check if directory is exists
            if ( ! Storage::disk('public')->exists('profile')) {
                Storage::disk('public')->makeDirectory('profile');
            }

            // resize image for user
            $userImage = Image::make($image)->fit(500, 500)->stream();
            Storage::disk('public')->put('profile/' . $imageName, $userImage);

        } else {

            $imageName = $user->image;

        }

        $user->name  = $request->name;
        $user->email = $request->email;
        $user->image = $imageName;
        $user->about = $request->about;
        $user->save();

        return redirect()->back()->with('successMsg', 'Profile is updated successfully!');

    }

    public function updatePassword(Request $request)
    {

        $this->validate($request, [
            'old_password' => 'required',
            'password'     => 'required|confirmed',
        ]);

        $hasPassword = Auth::user()->password;

        if (Hash::check($request->old_password, $hasPassword)) {

            if ( ! Hash::check($request->password, $hasPassword)) {

                $user           = User::findOrFail(Auth::id());
                $user->password = Hash::make($request->password);
                $user->save();

                Auth::logout();

                return redirect()->back();

            } else {
                return redirect()->back()->withErrors('New password cannot be same as old password.');
            }

        } else {
            return redirect()->back()->withErrors('Incorrect current password.');
        }

    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use function compact;
use function dd;
use function view;

class PostController extends Controller
{
    public function index()
    {
        $posts = Post::latest()->paginate(9);

        return view('posts', compact('posts'));
    }

    public function details($slug)
    {
        $post = Post::where('slug', $slug)->first();

        $blogKey = 'blog_' . $post->id;

        if ( ! Session::has($blogKey)) {
            $post->increment('view_count');
            Session::put($blogKey, 1);
        }

        $randomPosts = Post::all()->random(3);

        return view('post', compact('post', 'randomPosts'));
    }
}

resources/views/author/post/create.blade.php
@extends('layouts.backend.app')
@section('title', 'Create Post')

@push('css')
    <!-- Bootstrap Select Css -->
    <link href="{{asset('public/assets/backend/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet"/>
@endpush

@section('content')

    <div class="container-fluid">

        @if($errors->any())
            @foreach($errors->all() as $error)
                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert alert-danger" role="alert">
                            {{$error}}
                        </div>
                    </div>
                </div>
            @endforeach
        @endif

        <form action="{{route('author.post.store')}}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row clearfix">
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>ADD NEW Post</h2>
                        </div>

                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="title" name="title" class="form-control">
                                    <label for="title" class="form-label">Post Title</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="">
                                    <label for="tinymce" class="form-label">Post Content</label>
                                    <textarea name="body" id="tinymce" cols="30" rows="10" class="form-control"
                                              placeholder="Post Content"></textarea>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Additional Data</h2>
                        </div>

                        <div class="body">

                            <div class="form-group">
                                <div class="form-inline {{$errors->has('categories') ? 'focused error' : ''}}">
                                    <label for="category" class="form-label">Select Categories</label>
                                    <select name="categories[]" id="category" class="form-control show-tick"
                                            data-live-search="true" multiple>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-inline {{$errors->has('tags') ? 'focused error' : ''}}">
                                    <label for="tag" class="form-label">Select Tags</label>
                                    <select name="tags[]" id="tag" class="form-control show-tick"
                                            data-live-search="true" multiple>
                                        @foreach($tags as $tag)
                                            <option value="{{$tag->id}}">{{$tag->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <label for="image">Featured Image</label>
                                <input type="file" id="image" name="image" class="form-control">
                            </div>

                            {{--                            <div class="form-group form-float">
                                                            <input type="checkbox" name="status" id="publish" class="filled-in" value="1">
                                                            <label for="publish">Publish</label>
                                                        </div>--}}

                            <div class="demo-switch">
                                <div class="switch">
                                    <label for="publish">Un<input type="checkbox" name="status" id="publish"
                                                                  value="1"><span class="lever"></span>Publish</label>
                                </div>
                            </div>

                            <a href="{{route('author.post.index')}}"
                               class="btn btn-danger m-t-15 waves-effect">BACK</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SUBMIT</button>

                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@push('js')
    <!-- Select Plugin Js -->
    <script src="{{asset('public/assets/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>
    <!-- TinyMCE -->
    <script src="{{asset('public/assets/backend/plugins/tinymce/tinymce.js')}}"></script>

    <script type="text/javascript">
        $(function () {
            //TinyMCE
            tinymce.init({
                selector: "textarea#tinymce",
                theme: "modern",
                height: 300,
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools'
                ],
                toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons',
                image_advtab: true
            });
            tinymce.suffix = ".min";
            tinyMCE.baseURL = '{{asset('public/assets/backend/plugins/tinymce')}}';
        });
    </script>
@endpush

resources/views/author/post/index.blade.php
@extends('layouts.backend.app')
@section('title', 'Post')

@push('css')
    <link href="{{asset('public/assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}"
          rel="stylesheet">
@endpush

@section('content')

    <div class="container-fluid">
        <div class="block-header row clearfix">
            <div class="col-xs-6 col-sm-6 col-md-9 col-lg-10">
                <h2 class="align-left d-inline">CATEGORIES</h2>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-2 align-right">
                <a href="{{route('author.post.create')}}" class="btn btn-primary waves-effect">
                    <i class="material-icons">add</i><span>ADD Post</span></a>
            </div>
        </div>

        @if(session('successMsg'))
            <div class="row">
                <div class="col-xs-12">
                    <div class="alert alert-success" role="alert">
                        {{session('successMsg')}}
                    </div>
                </div>
            </div>
    @endif

    <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>ALL POSTS <span class="badge bg-info">{{$posts->count()}}</span></h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th class="text-center"><i class="material-icons">visibility</i></th>
                                    <th>Approved</th>
                                    <th>Status</th>
                                    <th>Last Updates</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th class="text-center"><i class="material-icons">visibility</i></th>
                                    <th>Approved</th>
                                    <th>Status</th>
                                    <th>Last Updates</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                @foreach($posts as $key => $post)
                                    <tr>
                                        <td>{{$key + 1}}</td>
                                        <td>{{str_limit($post->title, 75)}}</td>
                                        <td>{{$post->user->name}}</td>
                                        <td class="text-center">{{$post->view_count}}</td>
                                        <td>
                                            @if($post->is_approved)
                                                <span class="label bg-blue">Approved</span>
                                            @else
                                                <span class="label bg-pink">Pending</span>
                                            @endif

                                        </td>
                                        <td>
                                            @if($post->status)
                                                <span class="label bg-teal">Published</span>
                                            @else
                                                <span class="label bg-pink">Unpublished</span>
                                            @endif
                                        </td>
                                        <td>{{$post->updated_at->toFormattedDateString()}}</td>
                                        <td class="text-center">
                                            <a href="{{route('author.post.show', $post->id)}}"
                                               class="btn btn-primary btn-sm waves-effect"><i
                                                    class="material-icons">visibility</i></a>
                                            <a href="{{route('author.post.edit', $post->id)}}"
                                               class="btn btn-info btn-sm waves-effect"><i
                                                    class="material-icons">edit</i></a>
                                            <button class="btn btn-danger btn-sm waves-effect"
                                                    onclick="deletePost({{$post->id}})">
                                                <i class="material-icons">delete</i></button>
                                            <form action="{{route('author.post.destroy', $post->id)}}"
                                                  id="delete-form-{{$post->id}}" method="POST"
                                                  style="display: none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->

    </div>


@endsection

@push('js')

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('public/assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script
        src="{{asset('public/assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script
        src="{{asset('public/assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script
        src="{{asset('public/assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('public/assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('public/assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('public/assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script
        src="{{asset('public/assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script
        src="{{asset('public/assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{asset('public/assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        function deletePost($id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {

                    event.preventDefault();
                    document.getElementById('delete-form-' + $id).submit();

                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your imaginary file is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>

@endpush